api_platform:
  title: "VOTE EN LIGNE"
  description: "UN application realiser avec symfony et api plateforme pr le back"
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
